spring.application.name=orders
server.port =8081

jwt.secret=vortexbird-prueba-tecnica-sena-andres-lopez-16-06-2026
jwt.expiration=3600000

# --- H2 en memoria (fase inicial de desarrollo) ---
# --- spring.datasource.url=jdbc:h2:mem:ordersdb ---
# spring.datasource.username=
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/ordersdb
spring.datasource.username=orders
spring.datasource.password=orders
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

storage.s3.endpoint=http://localhost:9000
storage.s3.region=us-east-1
storage.s3.access-key=minioadmin
storage.s3.secret-key=minioadmin
storage.s3.bucket=invoices


notification.url=https://dummyjson.com/c/3029-d29f-4014-9fb4
