
--
-- Name: orders; Type: TABLE; Schema: public; Owner: orders
--

CREATE TABLE public.orders (
                               id bigint NOT NULL,
                               amount numeric(38,2) NOT NULL,
                               approved_by bigint,
                               code character varying(255) NOT NULL,
                               created_at timestamp(6) without time zone NOT NULL,
                               created_by bigint NOT NULL,
                               description character varying(255),
                               invoice_url character varying(255),
                               status character varying(255) NOT NULL,
                               updated_at timestamp(6) without time zone NOT NULL,
                               CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ARCHIVED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO orders;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: orders
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: orders
--

CREATE TABLE public.user_roles (
                                   user_id bigint NOT NULL,
                                   role character varying(255) NOT NULL,
                                   CONSTRAINT user_roles_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'OPERATOR'::character varying])::text[])))
);


ALTER TABLE public.user_roles OWNER TO orders;

--
-- Name: users; Type: TABLE; Schema: public; Owner: orders
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              first_name character varying(255) NOT NULL,
                              last_name character varying(255) NOT NULL,
                              email character varying(255) NOT NULL,
                              password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO orders;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: orders
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: orders
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: orders
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: orders ukgt3o4a5bqj59e9y6wakgk926t; Type: CONSTRAINT; Schema: public; Owner: orders
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT ukgt3o4a5bqj59e9y6wakgk926t UNIQUE (code);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: orders
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: orders
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: orders
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--
